# Generated by Django 5.2.7 on 2025-12-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='consent_job_publish',
            field=models.BooleanField(default=False, verbose_name='Godkänt publicering av jobb'),
        ),
        migrations.AddField(
            model_name='customer',
            name='consent_job_publish_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tidpunkt för samtycke'),
        ),
        migrations.AddField(
            model_name='customer',
            name='consent_job_publish_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP vid samtycke'),
        ),
        migrations.AddField(
            model_name='customer',
            name='personal_number',
            field=models.CharField(blank=True, help_text='YYYYMMDD-XXXX', max_length=13, null=True, verbose_name='Personnummer'),
        ),
    ]
