# Generated by Django 5.2.7 on 2025-12-23 06:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_email_verified_user_email_verified_at_and_more'),
        ('locations', '__first__'),
        ('taxonomy', '__first__'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='specialiteti',
        ),
        migrations.AddField(
            model_name='company',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='locations.city', verbose_name='Qyteti'),
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='organization_form',
            field=models.CharField(blank=True, max_length=50, verbose_name='Forma juridike'),
        ),
        migrations.AddField(
            model_name='company',
            name='professions',
            field=models.ManyToManyField(blank=True, related_name='companies', to='taxonomy.profession', verbose_name='Profesionet'),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='vat_registered',
            field=models.BooleanField(null=True, verbose_name='TVSH e regjistruar'),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, verbose_name='Faqja e internetit'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, verbose_name='Përshkrimi i kompanisë'),
        ),
        migrations.AlterField(
            model_name='company',
            name='org_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numri i biznesit'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Numri i telefonit'),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='company_profile', to=settings.AUTH_USER_MODEL, verbose_name='Përdoruesi'),
        ),
    ]
