# Generated by Django 5.2.7 on 2026-01-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_company_specialiteti_company_archived_at_and_more'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='company_service_areas', to='locations.city', verbose_name='Qytetet e shërbimit'),
        ),
    ]
