# Generated by Django 5.2.7 on 2026-01-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='profile_step',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Profile step'),
        ),
    ]
