# Generated by Django 5.2.7 on 2026-01-11 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_company_profile_step'),
        ('locations', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='emailverificationtoken',
            name='accounts_em_user_id_33bc9c_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailverificationtoken',
            name='accounts_em_expires_f36bd3_idx',
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='company_service_areas', to='locations.city'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='locations.city'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='org_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='organization_form',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='company',
            name='professions',
            field=models.ManyToManyField(blank=True, related_name='companies', to='taxonomy.profession'),
        ),
        migrations.AlterField(
            model_name='company',
            name='profile_step',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='vat_registered',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='consent_job_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='consent_job_publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='consent_job_publish_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='personal_number',
            field=models.CharField(blank=True, help_text='YYYYMMDD-XXXX', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
