# Generated by Django 5.2.7 on 2026-01-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_offer_presentation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
