# Generated by Django 5.2.7 on 2026-01-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_company_default_offer_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='free_leads_remaining',
            field=models.PositiveIntegerField(default=25, help_text='Number of free lead unlocks remaining for the company'),
        ),
    ]
