# Generated by Django 5.2.7 on 2026-04-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_company_free_leads_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='personal_number',
            field=models.CharField(blank=True, help_text='Kosovë: 13 shifra | Shqipëri: 1 shkronjë + 9 shifra', max_length=20, null=True),
        ),
    ]
