# Generated by Django 5.2.7 on 2026-04-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customer_country_alter_customer_personal_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='registration_document',
            field=models.FileField(blank=True, null=True, upload_to='company_documents/'),
        ),
        migrations.AddField(
            model_name='company',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
