# Generated by Codex on 2026-07-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_customer_city_customer_postal_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_completion_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
