# Generated by Codex on 2026-07-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_user_profile_completion_reminder_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="welcome_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
