# Generated by Django 5.2.7 on 2026-09-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_profile_completion_reminder_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='free_offers_remaining',
            field=models.PositiveIntegerField(default=25, help_text='One-time introductory allowance; consumed only when an offer is sent.'),
        ),
    ]
