# Generated by Django 5.2.7 on 2025-11-25 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequestAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('offer_sent', 'Ofertë e dërguar'), ('offer_accepted', 'Oferta u pranua'), ('offer_declined', 'Oferta u refuzua'), ('job_closed', 'Kërkesa u mbyll'), ('reopened_round_two', 'Rihapja e rundit të dytë'), ('winner_selected', 'Fituesi u përzgjodh')], max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auditim i kërkesës',
                'verbose_name_plural': 'Auditime të kërkesave',
            },
        ),
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titulli i punës')),
                ('description', models.TextField(verbose_name='Përshkrimi')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Buxheti €')),
                ('location', models.CharField(max_length=255, verbose_name='Vendndodhja')),
                ('kategoria', models.CharField(choices=[('hidrosanitare', 'Punë hidrosanitare'), ('elektrike', 'Punë elektrike'), ('ndërtim', 'Punë ndërtimore / zdrukthtari'), ('kulm', 'Punë për kulm'), ('lyerje', 'Punë lyerje / bojatisje'), ('tjera', 'Punë tjera')], default='ndërtim', max_length=100, verbose_name='Kategoria')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Krijuar më')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktive')),
                ('max_offers', models.PositiveIntegerField(default=7, verbose_name='Numri maksimal i ofertave')),
                ('last_offer_at', models.DateTimeField(blank=True, null=True, verbose_name='Data e ofertës së fundit')),
                ('is_reopened', models.BooleanField(default=False, verbose_name='Rihapur')),
                ('reopened_at', models.DateTimeField(blank=True, null=True, verbose_name='Rihapur më')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Përfunduar')),
                ('accepted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Çmimi i pranuar')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Skadon më')),
                ('winner_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Çmimi fitues')),
                ('accepted_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company', verbose_name='Kompania e pranuar')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to='accounts.customer', verbose_name='Klienti')),
                ('winner_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner_jobs', to='accounts.company', verbose_name='Fituesi')),
            ],
            options={
                'verbose_name': 'Kërkesë për Punë',
                'verbose_name_plural': 'Kërkesa për Punë',
            },
        ),
    ]
