# Generated by Django 5.2.7 on 2025-11-25 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobrequests', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='winner_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_offer', to='leads.leadmatch', verbose_name='Oferta fituese'),
        ),
        migrations.AddField(
            model_name='jobrequestaudit',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_company', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='jobrequestaudit',
            name='job_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='jobrequests.jobrequest'),
        ),
    ]
