# Generated by Django 5.2.7 on 2025-12-11 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobrequests', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequestDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('kategoria', models.CharField(blank=True, choices=[('hidrosanitare', 'Punë hidrosanitare'), ('elektrike', 'Punë elektrike'), ('ndërtim', 'Punë ndërtimore / zdrukthtari'), ('kulm', 'Punë për kulm'), ('lyerje', 'Punë lyerje / bojatisje'), ('tjera', 'Punë tjera')], default='ndërtim', max_length=100)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('is_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobrequest_drafts', to='accounts.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
