# Generated by Django 5.2.7 on 2026-01-01 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequests', '0003_jobrequestdraft'),
        ('locations', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequest',
            name='kategoria',
        ),
        migrations.RemoveField(
            model_name='jobrequest',
            name='location',
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='job_requests', to='locations.city', verbose_name='Qyteti'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='profession',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='job_requests', to='taxonomy.profession', verbose_name='Profesioni'),
            preserve_default=False,
        ),
    ]
