# Generated by Django 5.2.7 on 2026-01-01 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequests', '0004_remove_jobrequest_kategoria_and_more'),
        ('locations', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequestdraft',
            name='kategoria',
        ),
        migrations.RemoveField(
            model_name='jobrequestdraft',
            name='location',
        ),
        migrations.AddField(
            model_name='jobrequestdraft',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobrequest_drafts', to='locations.city', verbose_name='Qyteti'),
        ),
        migrations.AddField(
            model_name='jobrequestdraft',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobrequest_drafts', to='taxonomy.profession', verbose_name='Profesioni'),
        ),
    ]
