# Generated by Django 5.2.7 on 2026-03-01 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_company_free_leads_remaining'),
        ('jobrequests', '0005_remove_jobrequestdraft_kategoria_and_more'),
        ('offers', '0004_offer_round_number_alter_offer_current_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Përditësuar më'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='accepted_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_jobs', to='accounts.company', verbose_name='Kompania e pranuar'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Aktive'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Përfunduar'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='winner_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_jobs', to='offers.offer', verbose_name='Oferta fituese'),
        ),
        migrations.AlterField(
            model_name='jobrequestaudit',
            name='action',
            field=models.CharField(choices=[('offer_sent', 'Ofertë e dërguar'), ('offer_accepted', 'Oferta u pranua'), ('offer_declined', 'Oferta u refuzua'), ('job_closed', 'Kërkesa u mbyll'), ('reopened_round_two', 'Rihapja e rundit të dytë'), ('winner_selected', 'Fituesi u përzgjodh'), ('job_updated', 'Kërkesa u përditësua'), ('created_from_draft', 'Kërkesa u krijua nga draft')], max_length=50),
        ),
    ]
