# Generated by Django 5.2.7 on 2026-04-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequests', '0007_jobrequest_address_jobrequest_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequestaudit',
            name='action',
            field=models.CharField(choices=[('offer_sent', 'Ofertë e dërguar'), ('offer_accepted', 'Oferta u pranua'), ('offer_declined', 'Oferta u refuzua'), ('job_closed', 'Kërkesa u mbyll'), ('reopened_round_two', 'Rihapja e rundit të dytë'), ('winner_selected', 'Fituesi u përzgjodh'), ('job_updated', 'Kërkesa u përditësua'), ('created_from_draft', 'Kërkesa u krijua nga draft'), ('job_deleted', 'Kërkesa u fshi')], max_length=50),
        ),
    ]
