# Generated by Django 5.2.7 on 2026-04-30 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customer_city_customer_postal_code'),
        ('jobrequests', '0008_alter_jobrequestaudit_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kërkesë për Punë', 'verbose_name_plural': 'Kërkesa për Punë'},
        ),
        migrations.AlterModelOptions(
            name='jobrequestaudit',
            options={'ordering': ['-created_at'], 'verbose_name': 'Auditim i kërkesës', 'verbose_name_plural': 'Auditime të kërkesave'},
        ),
        migrations.RemoveField(
            model_name='jobrequest',
            name='accepted_company',
        ),
        migrations.RemoveField(
            model_name='jobrequest',
            name='accepted_price',
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='jobrequestaudit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Skadon më'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Përditësuar më'),
        ),
        migrations.AlterField(
            model_name='jobrequestaudit',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_audit_logs', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='jobrequestaudit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='jobrequestdraft',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='jobrequestdraft',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_request_drafts', to=settings.AUTH_USER_MODEL),
        ),
    ]
