# Generated by Django 5.2.7 on 2026-09-20 13:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequests', '0010_jobrequest_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='activity_tracking_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='customer_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='inactive_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='inactivity_reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
