# Generated by Django 5.2.7 on 2026-09-20 16:56

from django.db import migrations, models


def preserve_ongoing_work(apps, schema_editor):
    Job = apps.get_model("jobrequests", "JobRequest")
    Job.objects.using(schema_editor.connection.alias).filter(winner_offer__isnull=False, completed_at__isnull=True).update(status="in_progress", is_completed=False)


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequests', '0011_jobrequest_activity_tracking_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(preserve_ongoing_work, migrations.RunPython.noop),
    ]
