# Generated by Django 5.2.7 on 2026-10-01 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequests', '0012_jobrequest_completed_at'),
        ('locations', '0001_initial'),
        ('taxonomy', '0002_industry_alter_profession_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequestdraft',
            name='client_draft_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='jobrequestdraft',
            name='submitted_job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_draft', to='jobrequests.jobrequest'),
        ),
        migrations.AddConstraint(
            model_name='jobrequestdraft',
            constraint=models.UniqueConstraint(fields=('customer', 'client_draft_id'), name='unique_guest_draft_per_customer'),
        ),
    ]
