# Generated by Django 5.2.7 on 2026-10-05 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequests', '0013_jobrequestdraft_client_draft_id_and_more'),
        ('taxonomy', '0002_industry_alter_profession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='category_mode',
            field=models.CharField(blank=True, choices=[('', 'Kategori'), ('mixed', 'Punime të ndryshme'), ('unsure', 'Nuk jam i sigurt')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taxonomy.industry'),
        ),
        migrations.AddField(
            model_name='jobrequestdraft',
            name='category_mode',
            field=models.CharField(blank=True, choices=[('', 'Kategori'), ('mixed', 'Punime të ndryshme'), ('unsure', 'Nuk jam i sigurt')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='jobrequestdraft',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taxonomy.industry'),
        ),
    ]
