"""A dry run by default. No credit, cancellation or fee is generated by inactivity."""
from datetime import timedelta
from django.conf import settings
from django.core.mail import send_mail
from django.core.management.base import BaseCommand
from django.db import transaction
from django.db.models import Min
from django.utils import timezone
from jobrequests.models import JobRequest
from offers.models import OfferMessage
from leads.models import LeadMessage
from pushnotifications.services import schedule_push_notification


class Command(BaseCommand):
    help = "Remind after 7 days and mark platform inactivity after 14 days; --apply enables writes and notifications."

    def add_arguments(self, parser):
        parser.add_argument("--apply", action="store_true")

    def handle(self, *args, **options):
        now = timezone.now()
        reminded = marked = 0
        for job_id in JobRequest.objects.filter(is_active=True, is_deleted=False, is_completed=False).values_list("pk", flat=True).iterator():
            with transaction.atomic():
                job = JobRequest.objects.select_for_update().get(pk=job_id)
                if not job.is_active or job.is_deleted or job.is_completed:
                    continue
                active = (job.customer_activity_at or job.offers.filter(customer_opened_at__isnull=False).exists()
                          or job.offers.filter(versions__customer_rejected_at__isnull=False).exists()
                          or OfferMessage.objects.filter(offer__job_request=job, sender_type="customer").exists()
                          or LeadMessage.objects.filter(lead__job_request=job, sender_type="customer").exists())
                if active:
                    if options["apply"] and not job.customer_activity_at:
                        JobRequest.objects.filter(pk=job.pk).update(customer_activity_at=now, inactive_marked_at=None)
                    continue
                first_sent = job.offers.filter(versions__is_signed=True).aggregate(first=Min("versions__signed_at"))["first"]
                if not first_sent:
                    continue
                start = max(first_sent, job.activity_tracking_started_at)
                if now < start + timedelta(days=7):
                    continue
                if not job.inactivity_reminded_at:
                    reminded += 1
                    if options["apply"]:
                        link = settings.FRONTEND_BASE_URL.rstrip("/") + f"/customer/jobrequests/{job.pk}"
                        try:
                            sent = send_mail("A ju nevojitet ende ndihmë për kërkesën tuaj?",
                                f"Keni oferta të pahapura në Ndërtimnet. Hapni ofertat dhe përgjigjuni kompanive. A ju nevojitet ende kjo punë?\n{link}",
                                settings.DEFAULT_FROM_EMAIL, [job.customer.email])
                        except Exception:
                            self.stderr.write(f"Reminder delivery failed for job {job.pk}; will retry.")
                            continue
                        if not sent:
                            continue
                        job.inactivity_reminded_at = now
                        job.save(update_fields=["inactivity_reminded_at"])
                        schedule_push_notification(user=job.customer, category="offer_updates",
                            title="Keni oferta të pahapura", body="A ju nevojitet ende puna? Hapni ofertat dhe përgjigjuni kompanive.",
                            data={"path": f"/customer/jobrequests/{job.pk}"})
                if now >= start + timedelta(days=14) and not job.inactive_marked_at:
                    marked += 1
                    if options["apply"]:
                        job.inactive_marked_at = now
                        job.save(update_fields=["inactive_marked_at"])
        self.stdout.write(f"{'Applied' if options['apply'] else 'Dry run'}: reminders={reminded}, inactive={marked}. No credits issued.")
