# Generated by Django 5.2.7 on 2026-07-10 12:23

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


TAXONOMY = [
    (
        "Ndërtim dhe renovim",
        "ndertim-dhe-renovim",
        [
            "Nuk e di",
            "Ndërtim i përgjithshëm",
            "Renovim banjo",
            "Renovim kuzhine",
            "Elektricist",
            "Hidraulik",
            "Lyerje",
            "Fasada dhe izolim",
            "Punime çatie",
            "Dysheme",
            "Dyer dhe dritare",
            "Punime të brendshme",
        ],
    ),
    (
        "Pastrim dhe mirëmbajtje",
        "pastrim-dhe-mirembajtje",
        [
            "Pastrim shtëpie",
            "Pastrim pas shpërnguljes",
            "Pastrim pas ndërtimit",
            "Pastrim zyre",
            "Pastrim shkallësh",
            "Larje dritaresh",
            "Pastrim i thellë",
            "Larje qilimash dhe mobiliesh",
        ],
    ),
    (
        "Shpërngulje dhe transport",
        "shperngulje-dhe-transport",
        [
            "Ndihmë për shpërngulje",
            "Bartje",
            "Transport mobiliesh",
            "Magazinim",
            "Paketim",
            "Montim dhe çmontim",
            "Largim mbeturinash",
            "Mbeturina ndërtimi",
        ],
    ),
    (
        "Kopsht dhe ambient i jashtëm",
        "kopsht-dhe-ambient-i-jashtem",
        [
            "Kositje bari",
            "Krasitje",
            "Prerje gardhi",
            "Dizajn kopshti",
            "Gardhe",
            "Shtrim guri",
            "Verandë dhe terasë",
            "Pastrimi i borës",
        ],
    ),
    (
        "Siguri dhe bravari",
        "siguri-dhe-bravari",
        [
            "Ndërrim dryni",
            "Hapje dryni",
            "Alarm",
            "Kamera sigurie",
            "Sistem hyrjeje",
            "Mbrojtje nga zjarri",
            "Dyer sigurie",
            "Zgjidhje smart home",
        ],
    ),
    (
        "Shërbime prone dhe mirëmbajtje",
        "sherbime-prone-dhe-mirembajtje",
        [
            "Mirëmbajtje prone",
            "Riparime të thjeshta",
            "Instalim pajisjesh shtëpiake",
            "Servis ventilimi",
            "Pompë nxehtësie",
            "Dezinsektim",
            "Lagështi dhe myk",
            "Shërbim emergjent",
        ],
    ),
]


def seed_taxonomy(apps, schema_editor):
    Industry = apps.get_model("taxonomy", "Industry")
    Profession = apps.get_model("taxonomy", "Profession")

    for industry_order, (industry_name, industry_slug, professions) in enumerate(TAXONOMY, start=1):
        industry, _ = Industry.objects.update_or_create(
            slug=industry_slug,
            defaults={
                "name": industry_name,
                "is_active": True,
                "sort_order": industry_order,
            },
        )

        for profession_order, profession_name in enumerate(professions, start=1):
            Profession.objects.update_or_create(
                slug=slugify(profession_name),
                defaults={
                    "industry": industry,
                    "name": profession_name,
                    "is_active": True,
                    "sort_order": profession_order,
                },
            )

    default_industry = Industry.objects.get(slug="ndertim-dhe-renovim")
    Profession.objects.filter(industry__isnull=True).update(industry=default_industry)


def unseed_taxonomy(apps, schema_editor):
    Industry = apps.get_model("taxonomy", "Industry")
    Industry.objects.filter(slug__in=[item[1] for item in TAXONOMY]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Bransch',
                'verbose_name_plural': 'Branscher',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'ordering': ['industry__sort_order', 'sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='profession',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profession',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professions', to='taxonomy.industry'),
        ),
        migrations.RunPython(seed_taxonomy, migrations.RunPython.noop),
    ]
