# Generated by Codex on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlatformUpdate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=180)),
                ("date_label", models.CharField(max_length=80)),
                ("status", models.CharField(choices=[("in_progress", "Në zhvillim"), ("planned", "Në plan"), ("done", "Të publikuara")], default="planned", max_length=20)),
                ("is_new", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Platform update",
                "verbose_name_plural": "Platform updates",
                "ordering": ("status", "display_order", "-created_at"),
            },
        ),
    ]
