# Generated by Django 5.2.7 on 2026-09-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_hero_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmissionGuard',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('attempts', models.JSONField(default=list)),
            ],
        ),
    ]
