# Generated by Django 5.2.7 on 2026-01-15 05:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_company_default_offer_presentation'),
        ('jobrequests', '0005_remove_jobrequestdraft_kategoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('signed', 'Signed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='accounts.company')),
                ('job_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='jobrequests.jobrequest')),
            ],
        ),
        migrations.CreateModel(
            name='OfferVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('presentation_text', models.TextField(blank=True, default='')),
                ('can_start_from', models.DateField(blank=True, null=True)),
                ('duration_text', models.CharField(blank=True, default='', max_length=120)),
                ('price_type', models.CharField(choices=[('fixed', 'Fast pris'), ('hourly', 'Timpris')], default='fixed', max_length=20)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('includes_text', models.TextField(blank=True, default='')),
                ('excludes_text', models.TextField(blank=True, default='')),
                ('payment_terms', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='offers.offer')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('offer', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='OfferSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnummer_hash', models.CharField(max_length=64)),
                ('personnummer_masked', models.CharField(max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('offer_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='offers.offerversion')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='offers.offerversion'),
        ),
        migrations.CreateModel(
            name='OfferChatUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlock_type', models.CharField(choices=[('early', 'Early (före accept)'), ('after_accept', 'After accept (gratis)')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=128)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_unlocks', to='offers.offer')),
            ],
            options={
                'unique_together': {('offer', 'unlock_type')},
            },
        ),
    ]
