# Generated by Django 5.2.7 on 2026-01-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_company_default_offer_presentation'),
        ('jobrequests', '0005_remove_jobrequestdraft_kategoria_and_more'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(fields=('company', 'job_request'), name='unique_offer_per_company_job'),
        ),
    ]
