# Generated by Django 5.2.7 on 2026-01-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_unique_offer_per_company_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='lead_unlocked',
            field=models.BooleanField(default=False, help_text='Whether the company has unlocked access to this lead'),
        ),
    ]
