# Generated by Django 5.2.7 on 2026-02-27 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_company_free_leads_remaining'),
        ('offers', '0003_offer_lead_unlocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='round_number',
            field=models.PositiveSmallIntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='offer',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='offers.offerversion'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('signed', 'Signed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('locked', 'Locked')], db_index=True, default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='OfferMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('company', 'Kompani'), ('customer', 'Klient')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='offers.offer')),
                ('sender_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_offer_messages', to='accounts.company')),
                ('sender_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_offer_messages', to='accounts.customer')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
