# Generated by Django 5.2.7 on 2026-03-01 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_company_free_leads_remaining'),
        ('jobrequests', '0006_jobrequest_deleted_at_jobrequest_is_deleted_and_more'),
        ('offers', '0004_offer_round_number_alter_offer_current_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='offermessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['job_request', 'status'], name='offers_offe_job_req_2b16d3_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['company', 'status'], name='offers_offe_company_c2e8f5_idx'),
        ),
        migrations.AddIndex(
            model_name='offerchatunlock',
            index=models.Index(fields=['offer', 'unlock_type'], name='offers_offe_offer_i_deeabc_idx'),
        ),
        migrations.AddIndex(
            model_name='offermessage',
            index=models.Index(fields=['offer', 'created_at'], name='offers_offe_offer_i_323f16_idx'),
        ),
        migrations.AddIndex(
            model_name='offerversion',
            index=models.Index(fields=['offer', 'version_number'], name='offers_offe_offer_i_b196b7_idx'),
        ),
    ]
