# Generated by Django 5.2.7 on 2026-07-11 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_welcome_email_sent_at'),
        ('offers', '0006_offerreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offerreview',
            name='moderation_status',
            field=models.CharField(choices=[('published', 'Published'), ('pending', 'Pending review'), ('hidden', 'Hidden')], db_index=True, default='published', max_length=20),
        ),
        migrations.AddIndex(
            model_name='offerreview',
            index=models.Index(fields=['company', 'moderation_status', '-created_at'], name='offers_offe_company_1b82e9_idx'),
        ),
    ]
