# Generated by Django 5.2.7 on 2026-09-19 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_offermessage_delivery_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offermessage',
            options={'ordering': ['created_at'], 'permissions': [('review_chat', 'Review stored chats and manage retention holds')]},
        ),
        migrations.AddField(
            model_name='offer',
            name='chat_retention_hold',
            field=models.BooleanField(default=False, help_text='Keep chat for an ongoing support or dispute case.'),
        ),
        migrations.AddField(
            model_name='offer',
            name='chat_retention_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='ChatReviewAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='view', max_length=20)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.offer')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
