# Generated by Django 5.2.7 on 2026-09-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_alter_offermessage_options_offer_chat_retention_hold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerversion',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
