# Generated by Django 5.2.7 on 2026-09-20 13:13

import django.db.models.deletion
from django.db import migrations, models


def preserve_accepted_versions(apps, schema_editor):
    Offer = apps.get_model("offers", "Offer")
    Version = apps.get_model("offers", "OfferVersion")
    for offer in Offer.objects.filter(status="accepted", current_version__isnull=False).iterator():
        Offer.objects.filter(pk=offer.pk).update(accepted_version_id=offer.current_version_id)
        Version.objects.filter(pk=offer.current_version_id).update(customer_accepted_at=offer.accepted_at)


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_offerversion_estimated_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='accepted_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='offers.offerversion'),
        ),
        migrations.AddField(
            model_name='offer',
            name='customer_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerversion',
            name='customer_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerversion',
            name='customer_rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(preserve_accepted_versions, migrations.RunPython.noop),
    ]
