# Generated by Django 5.2.7 on 2025-12-27 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_remove_company_specialiteti_company_archived_at_and_more'),
        ('leads', '0002_leadmatch_can_chat_leadmatch_customer_info_unlocked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('offer_access', 'Offer Access'), ('chat_access', 'Chat Access')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('provider_ref', models.CharField(blank=True, help_text='Transaction / PaymentIntent ID', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_payments', to='accounts.company')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='leads.leadmatch')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('company', 'lead', 'purpose')},
            },
        ),
    ]
