# Generated by Django 5.2.7 on 2025-12-27 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_company_specialiteti_company_archived_at_and_more'),
        ('jobrequests', '0003_jobrequestdraft'),
        ('leads', '0002_leadmatch_can_chat_leadmatch_customer_info_unlocked_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='systempayment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='systempayment',
            name='job_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_payments', to='jobrequests.jobrequest'),
        ),
        migrations.AddField(
            model_name='systempayment',
            name='lead_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_payments', to='leads.leadmatch'),
        ),
        migrations.AlterField(
            model_name='systempayment',
            name='provider',
            field=models.CharField(choices=[('system', 'System'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('manual', 'Manual')], default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='systempayment',
            name='provider_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='systempayment',
            name='purpose',
            field=models.CharField(choices=[('offer_access', 'Offer Access'), ('chat_access', 'Chat Access')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='systempayment',
            constraint=models.UniqueConstraint(fields=('company', 'job_request', 'purpose'), name='uniq_company_jobrequest_purpose'),
        ),
        migrations.AddConstraint(
            model_name='systempayment',
            constraint=models.UniqueConstraint(fields=('company', 'lead_match', 'purpose'), name='uniq_company_leadmatch_purpose'),
        ),
        migrations.RemoveField(
            model_name='systempayment',
            name='lead',
        ),
    ]
