# Generated by Django 5.2.7 on 2026-01-25 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_company_free_leads_remaining'),
        ('jobrequests', '0005_remove_jobrequestdraft_kategoria_and_more'),
        ('offers', '0003_offer_lead_unlocked'),
        ('payments', '0002_alter_systempayment_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_accesses', to='accounts.company')),
                ('job_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_accesses', to='jobrequests.jobrequest')),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('company', 'job_request')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('unlock_lead', 'Unlock lead'), ('unlock_chat', 'Unlock chat')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount charged. Can be 0 for free unlocks.', max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('provider', models.CharField(choices=[('internal', 'Internal'), ('stripe', 'Stripe'), ('manual', 'Manual')], default='internal', max_length=20)),
                ('provider_reference', models.CharField(blank=True, help_text='Reference ID from payment provider (Stripe session ID, etc.)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.company')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='offers.offer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SystemPayment',
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('offer', 'type'), name='unique_payment_per_offer_type'),
        ),
    ]
