# Generated by Django 5.2.7 on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_leadaccess_payment_delete_systempayment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[
                    ("internal", "Internal"),
                    ("raiaccept", "RaiAccept"),
                    ("stripe", "Stripe"),
                    ("manual", "Manual"),
                ],
                default="internal",
                max_length=20,
            ),
        ),
    ]
