# Generated by Django 5.2.7 on 2026-09-17 03:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_profile_completion_reminder_count'),
        ('jobrequests', '0010_jobrequest_moderation'),
        ('offers', '0008_offermessage_delivery_state'),
        ('payments', '0006_payment_payer_user_and_job_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(max_length=32)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_offers', models.PositiveSmallIntegerField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('terms_version', models.CharField(default='2026-09-three-month-notice', max_length=40)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_subscriptions', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='BillingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('offers_used', models.PositiveSmallIntegerField(default=0)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='payments.billingsubscription')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('listing', 'Publikimi i kërkesës'), ('offer_fee', 'Dërgimi i ofertës'), ('subscription', 'Abonimi mujor')], max_length=20)),
                ('regular_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.company')),
                ('included_in_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='included_charges', to='payments.billingperiod')),
                ('job_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publication_charge', to='jobrequests.jobrequest')),
                ('offer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='platform_charge', to='offers.offer')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_charges', to=settings.AUTH_USER_MODEL)),
                ('period', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charge', to='payments.billingperiod')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('checkout_url', models.URLField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to='payments.platformcharge')),
            ],
        ),
        migrations.AddConstraint(
            model_name='billingperiod',
            constraint=models.UniqueConstraint(fields=('subscription', 'number'), name='unique_billing_period'),
        ),
        migrations.AddConstraint(
            model_name='platformcharge',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='platform_charge_nonnegative'),
        ),
    ]
