# Generated by Django 5.2.7 on 2026-09-19 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_company_free_offers_remaining'),
        ('jobrequests', '0010_jobrequest_moderation'),
        ('offers', '0009_alter_offermessage_options_offer_chat_retention_hold_and_more'),
        ('payments', '0007_billingsubscription_billingperiod_platformcharge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformcharge',
            name='kind',
            field=models.CharField(choices=[('listing', 'Publikimi i kërkesës'), ('offer_fee', 'Dërgimi i ofertës'), ('offer_adjustment', 'Diferenca e tarifës së ofertës'), ('subscription', 'Abonimi mujor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='platformcharge',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='platform_charges', to='offers.offer'),
        ),
        migrations.AddConstraint(
            model_name='platformcharge',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'offer_fee')), fields=('offer',), name='one_initial_offer_charge'),
        ),
        migrations.AddConstraint(
            model_name='platformcharge',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'offer_adjustment'), ('status', 'pending')), fields=('offer',), name='one_pending_offer_adjustment'),
        ),
    ]
