# Generated by Django 5.2.7 on 2026-09-19 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_alter_offermessage_options_offer_chat_retention_hold_and_more'),
        ('payments', '0008_alter_platformcharge_kind_alter_platformcharge_offer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferPriceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_reports', to='offers.offer')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('version', models.CharField(max_length=80)),
                ('sha256', models.CharField(max_length=64)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='agreement', to='payments.billingsubscription')),
            ],
        ),
    ]
