# Generated by Django 5.2.7 on 2026-09-20 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_company_free_offers_remaining'),
        ('offers', '0011_offer_accepted_version_offer_customer_opened_at_and_more'),
        ('payments', '0009_offerpricereport_subscriptionagreement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('false_request', 'Kërkesë e rreme e konfirmuar'), ('duplicate', 'Kërkesë e dyfishtë e konfirmuar'), ('technical_failure', 'Dështim teknik i konfirmuar')], max_length=30)),
                ('evidence', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_credits', to='accounts.company')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('redeemed_offer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redeemed_credit', to='offers.offer')),
                ('source_offer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='compensation_credit', to='offers.offer')),
            ],
            options={
                'permissions': [('issue_offer_credit', 'Issue an offer credit after confirming an eligible fault')],
            },
        ),
    ]
