# Generated by Django 5.2.7 on 2026-09-20 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_offercredit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='platformcheckout',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformcheckout',
            name='reconciliation_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='offercredit',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offercredit',
            name='reason',
            field=models.CharField(choices=[('false_request', 'Kërkesë e rreme e konfirmuar'), ('duplicate', 'Kërkesë e dyfishtë e konfirmuar'), ('job_closed_before_send', 'Kërkesa u mbyll përpara dërgimit'), ('technical_failure', 'Dështim teknik i konfirmuar')], max_length=30),
        ),
    ]
