# Generated by Django 5.2.7 on 2025-11-25 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobrequests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date_accepted', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company')),
            ],
            options={
                'verbose_name': 'Punë e Arkivuar',
                'verbose_name_plural': 'Punë të Arkivuara',
            },
        ),
        migrations.CreateModel(
            name='LeadMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mesazhi i kompanisë')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Çmimi i ofertës')),
                ('status', models.CharField(choices=[('pending', 'Në pritje'), ('accepted', 'E pranuar'), ('declined', 'E refuzuar')], default='pending', max_length=20, verbose_name='Statusi i ofertës')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dërguar më')),
                ('round_number', models.PositiveIntegerField(default=1, verbose_name='Rundi')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_offers', to='accounts.company', verbose_name='Kompania')),
                ('job_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jobrequests.jobrequest', verbose_name='Kërkesa për punë')),
            ],
            options={
                'verbose_name': 'Ofertë Kompanie',
                'verbose_name_plural': 'Oferta Kompanish',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('company', 'Kompani'), ('customer', 'Klient')], max_length=20, verbose_name='Lloji')),
                ('message', models.TextField(verbose_name='Mesazhi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='leads.leadmatch', verbose_name='Oferta')),
                ('sender_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='accounts.company')),
                ('sender_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_messages', to='accounts.customer')),
            ],
            options={
                'verbose_name': 'Mesazh',
                'verbose_name_plural': 'Mesazhe',
                'ordering': ['created_at'],
            },
        ),
    ]
