# Generated by Django 5.2.7 on 2025-12-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadmatch',
            name='can_chat',
            field=models.BooleanField(default=False, help_text='Företaget kan chatta med kunden via plattformen.'),
        ),
        migrations.AddField(
            model_name='leadmatch',
            name='customer_info_unlocked',
            field=models.BooleanField(default=False, help_text='Sant när kundens kontaktuppgifter är upplåsta.'),
        ),
        migrations.AddField(
            model_name='leadmatch',
            name='customer_info_unlocked_by_company',
            field=models.BooleanField(default=False, help_text='Sant när företaget manuellt köper premium-unlock (5€).'),
        ),
        migrations.AddField(
            model_name='leadmatch',
            name='workflow_status',
            field=models.CharField(choices=[('active', 'Active'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='active', help_text='Pipeline-status för leadet.', max_length=20),
        ),
    ]
