# Generated by Django 5.2.7 on 2026-03-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_company_free_leads_remaining'),
        ('jobrequests', '0006_jobrequest_deleted_at_jobrequest_is_deleted_and_more'),
        ('leads', '0002_leadmatch_can_chat_leadmatch_customer_info_unlocked_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivedjob',
            options={'ordering': ['-date_accepted'], 'verbose_name': 'Punë e Arkivuar', 'verbose_name_plural': 'Punë të Arkivuara'},
        ),
        migrations.AlterModelOptions(
            name='leadmatch',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ofertë Kompanie (Legacy)', 'verbose_name_plural': 'Oferta Kompanish (Legacy)'},
        ),
        migrations.AlterModelOptions(
            name='leadmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Mesazh (Legacy)', 'verbose_name_plural': 'Mesazhe (Legacy)'},
        ),
        migrations.AlterField(
            model_name='leadmatch',
            name='can_chat',
            field=models.BooleanField(default=False, help_text='LEGACY: Företaget kan chatta med kunden via plattformen.'),
        ),
        migrations.AlterField(
            model_name='leadmatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Dërguar më'),
        ),
        migrations.AlterField(
            model_name='leadmatch',
            name='customer_info_unlocked',
            field=models.BooleanField(default=False, help_text='LEGACY: Sant när kundens kontaktuppgifter är upplåsta.'),
        ),
        migrations.AlterField(
            model_name='leadmatch',
            name='customer_info_unlocked_by_company',
            field=models.BooleanField(default=False, help_text='LEGACY: Sant när företaget manuellt köper premium-unlock (5€).'),
        ),
        migrations.AlterField(
            model_name='leadmatch',
            name='round_number',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='Rundi'),
        ),
        migrations.AlterField(
            model_name='leadmatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Në pritje'), ('accepted', 'E pranuar'), ('declined', 'E refuzuar')], db_index=True, default='pending', max_length=20, verbose_name='Statusi i ofertës'),
        ),
        migrations.AlterField(
            model_name='leadmatch',
            name='workflow_status',
            field=models.CharField(choices=[('active', 'Active'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='active', help_text='LEGACY: Pipeline-status för leadet.', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='archivedjob',
            index=models.Index(fields=['company', 'date_accepted'], name='leads_archi_company_4059bb_idx'),
        ),
        migrations.AddIndex(
            model_name='leadmatch',
            index=models.Index(fields=['job_request', 'company'], name='leads_leadm_job_req_30081b_idx'),
        ),
        migrations.AddIndex(
            model_name='leadmatch',
            index=models.Index(fields=['workflow_status'], name='leads_leadm_workflo_eb43fa_idx'),
        ),
        migrations.AddIndex(
            model_name='leadmatch',
            index=models.Index(fields=['status'], name='leads_leadm_status_d787f9_idx'),
        ),
        migrations.AddIndex(
            model_name='leadmessage',
            index=models.Index(fields=['lead', 'created_at'], name='leads_leadm_lead_id_4f1a4d_idx'),
        ),
    ]
